Repository microsoft/vs-streamjsonrpc, pull requests merged in 2020-10, with the labels that each got.

#574 Update connecting.md
  doc/connecting.md
Labels: docs

#573 LOC CHECKIN | Microsoft/vs-streamjsonrpc master | 20201005.
  src/StreamJsonRpc/xlf/Resources.cs.xlf
  src/StreamJsonRpc/xlf/Resources.de.xlf
  src/StreamJsonRpc/xlf/Resources.es.xlf
  src/StreamJsonRpc/xlf/Resources.fr.xlf
  src/StreamJsonRpc/xlf/Resources.it.xlf
  src/StreamJsonRpc/xlf/Resources.ja.xlf
  src/StreamJsonRpc/xlf/Resources.ko.xlf
  src/StreamJsonRpc/xlf/Resources.pl.xlf
  src/StreamJsonRpc/xlf/Resources.pt-BR.xlf
  src/StreamJsonRpc/xlf/Resources.ru.xlf
  src/StreamJsonRpc/xlf/Resources.tr.xlf
  src/StreamJsonRpc/xlf/Resources.zh-Hans.xlf
  src/StreamJsonRpc/xlf/Resources.zh-Hant.xlf
Labels: auto-squash

#583 Avoid loading Newtonsoft.Json in MessagePack scenarios
  src/StreamJsonRpc/CommonMethodNameTransforms.cs
  src/StreamJsonRpc/Utilities.cs
  test/StreamJsonRpc.Tests/AssemblyLoadTests.cs
Labels: enhancement

#594 Reduce string encoding/decoding in MessagePackFormatter
  src/StreamJsonRpc/MessagePackFormatter.cs
Labels: enhancement

#596 Optimize RPC target reflection
  src/StreamJsonRpc/JsonRpc.cs
  src/StreamJsonRpc/ProxyGeneration.cs
  src/StreamJsonRpc/Reflection/MethodSignature.cs
  src/StreamJsonRpc/Reflection/MethodSignatureAndTarget.cs
  src/StreamJsonRpc/Reflection/RpcTargetInfo.cs
Labels: auto-merge, enhancement

#595 Short-lived JsonRpc connection perf improvements
  src/StreamJsonRpc/JsonRpc.cs
  src/StreamJsonRpc/ProxyGeneration.cs
  src/StreamJsonRpc/Reflection/MessageFormatterEnumerableTracker.cs
  src/StreamJsonRpc/Reflection/MessageFormatterRpcMarshaledContextTracker.cs
Labels: auto-merge, enhancement

#598 GC pressure fixes
  src/StreamJsonRpc/MessageHandlerBase.cs
  src/StreamJsonRpc/MessagePackFormatter.cs
Labels: enhancement
